### ISSUE TITLE
Doesn't work on 2014 Retina MBP on OSX 10.10.3?

### ISSUE THREAD

**Issue by greggman** [electric-monk/360Controller#4]
I just got an XBOX 360 wired controller. Plug it into my mbp. In Chrome using the gamepad API it works great but it wasn't working in Axiom Verge.

Installed this software, version 0.12, but it says "No devices found" even though Chrome has no problem finding the controller. (yes I rebooted after installing)

Any ideas?

![screenshot](http://i.imgur.com/vtHHr1y.png)

**Comment by drjackyl** [comment]
Confirmed. Seems, the driver doesn't work anymore. Maybe a Yosemite-thing.

**Comment by greggman** [comment]
There's an forked/updated version here that works in Yosemite. 

https://github.com/d235j/360Controller/releases/tag/v0.14-unofficial

**Comment by drjackyl** [comment]
Yip found it, right after reading on, thx.

**Comment by electric-monk** [comment]
Yup, once I get some time to actually work on it I'll get it resigned. Same as the other issue.
