### ISSUE TITLE
Not working under Mac OS EL Capitan

### ISSUE THREAD

**Issue by BSVogler** [electric-monk/360Controller#8]
I made the big mistake by upgrading to bet El Capitan and now I can not present my game with controllers using my only Mac Laptop. I would appreciate a fix in the next two days but I do not expect you to fix it.
The preference pane still works but the controllers are not found.
Thanks for the good work.

**Comment by Endogen** [comment]
Anything new on this topic? I also use El Capitan and i wanted to use this driver but since BSVogler mentions it doesn't work... What to do??

EDIT: Seems this should work. Not tested yet
https://github.com/360Controller/360Controller

**Comment by BSVogler** [comment]
I will Try it again to make sure I set up everything correctly. Maybe some El Capitan Update fixed the issue.

**Comment by Endogen** [comment]
I think you understood me wrong. I'm not talking about the driver in this repository, take a look at this other repository: https://github.com/360Controller/360Controller

**Comment by BSVogler** [comment]
A bit confusing with the several forks. v1.5 runs on EL Capitan.

**Comment by ldong** [comment]
360Controller 0.15 (beta 3)
https://github.com/360Controller/360Controller/releases

Worked for me.
<img width="692" alt="screen shot 2015-12-01 at 8 22 45 pm" src="https://cloud.githubusercontent.com/assets/5491695/11522172/50eeca08-9869-11e5-9b9e-3120fd4a2645.png">

**Comment by BSVogler** [comment]
closing this now
